import test from "node:test";
import assert from "node:assert/strict";
import { createPhase12Service, phase12Api, phase12DashboardFixture, Phase12ApiError, sanitizeIntegrationMetadata } from "../src/phase12-api.js";

test("mock dashboard is explicitly scoped and aggregate contract remains unresolved", async () => { const result = await phase12Api.getDashboard(); assert.equal(result.meta.adapterMode, "mock"); assert.equal(result.meta.externalContacted, false); assert.equal(result.data.scope, "selected_project_mock"); assert.equal(result.data.aggregateContractStatus, "unresolved"); });
test("dashboard attention preserves proposal and non-execution semantics", () => { assert.ok(phase12DashboardFixture.attention.some((item) => item.proposed)); assert.ok(phase12DashboardFixture.attention.every((item) => item.executed === false)); });
test("activity preview is operational history rather than audit", () => { assert.ok(phase12DashboardFixture.activity.every((item) => item.audit === false)); });
test("approval summary never infers downstream execution", () => { assert.equal(phase12DashboardFixture.outputs.approvals.executed, 0); assert.equal(phase12DashboardFixture.execution.downstreamActionsExecuted, false); });
test("integration readiness keeps configuration and contract checks separate", async () => { const result = await phase12Api.getIntegrationReadiness(); const ids = new Set(result.data.map((item) => item.id)); assert.ok(ids.has("base_url")); assert.ok(ids.has("auth")); assert.ok(ids.has("aggregate")); assert.ok(ids.has("sse")); });
test("mock mode does not call fetch", async () => { let calls = 0; const service = createPhase12Service({ mode: "mock", fetchImpl: async () => { calls += 1; } }); await service.getDashboard(); assert.equal(calls, 0); });
test("live mode fails closed without configuration", async () => { const service = createPhase12Service({ mode: "live", baseUrl: "" }); await assert.rejects(() => service.getDashboard(), (error) => error instanceof Phase12ApiError && error.code === "LIVE_API_NOT_CONFIGURED"); });
test("live mode rejects unsafe non-local HTTP base URLs", async () => { const service = createPhase12Service({ mode: "live", baseUrl: "http://example.com" }); await assert.rejects(() => service.getDashboard(), (error) => error.code === "UNSAFE_API_BASE_URL"); });
test("live adapter uses a safe GET and request identifier", async () => { let request; const service = createPhase12Service({ mode: "live", baseUrl: "https://api.example.test", fetchImpl: async (url, options) => { request = { url, options }; return { ok: true, status: 200, headers: { get: () => "req_server_1" }, json: async () => ({ data: phase12DashboardFixture }) }; } }); const result = await service.getDashboard(); assert.equal(request.url, "https://api.example.test/api/v1/dashboard"); assert.equal(request.options.method, "GET"); assert.ok(request.options.headers["X-Request-ID"]); assert.equal(result.meta.requestId, "req_server_1"); });
test("malformed live responses fail with a canonical error", async () => { const service = createPhase12Service({ mode: "live", baseUrl: "https://api.example.test", fetchImpl: async () => ({ ok: true, status: 200, headers: { get: () => "req_bad" }, json: async () => ({ data: { workspaceId: "ws" } }) }) }); await assert.rejects(() => service.getDashboard(), (error) => error.code === "MALFORMED_RESPONSE" && error.requestId === "req_bad"); });
test("sensitive integration metadata is recursively redacted", () => { const safe = sanitizeIntegrationMetadata({ token: "x", nested: { clientSecret: "y", ok: true }, headers: { authorization: "z" }, responsePayload: { password: "p" } }); assert.equal(safe.token, "[REDACTED]"); assert.equal(safe.nested.clientSecret, "[REDACTED]"); assert.equal(safe.nested.ok, true); assert.equal(safe.headers, "[OMITTED]"); assert.equal(safe.responsePayload, "[OMITTED]"); });
test("dashboard fixture exposes no external action claims", () => { assert.deepEqual(phase12DashboardFixture.execution, { externalContacted: false, importedRecords: 0, secretsExposed: false, downstreamActionsExecuted: false }); });
