export type AdapterMode = "mock" | "live";
export type ContractCheckStatus = "ready" | "mock" | "live_configured" | "not_configured" | "not_run" | "contract_partial" | "blocked" | "unavailable";
export interface ContractCheck { id: string; label: string; status: ContractCheckStatus; detail: string; }
export interface IntegrationReadiness { adapterMode: AdapterMode; baseUrlConfigured: boolean; checks: ContractCheck[]; }
export interface AttentionItem { id: string; kind: "approval" | "workflow" | "finding" | "context" | "integration"; severity: "critical" | "high" | "medium" | "low"; title: string; detail: string; href: string; proposed: boolean; executed: boolean; }
export interface ProjectHealthSummary { id: string; name: string; lifecycle: "draft" | "active" | "paused" | "completed" | "archived"; health: "healthy" | "attention" | "degraded" | "unknown"; summary: string; }
export interface DashboardOverview { id: string; workspaceId: string; selectedProjectId: string; scope: "selected_project_mock" | "workspace_aggregate"; aggregateContractStatus: "available" | "unresolved"; source: "deterministic_mock" | "live_backend"; generatedAt: string; metrics: Array<{ id: string; label: string; value: string | number; tone: string; detail: string }>; attention: AttentionItem[]; projects: ProjectHealthSummary[]; workflows: Array<{ id: string; label: string; status: string; progressPercent: number }>; outputs: { reports: Record<string, number>; approvals: Record<string, number> }; readiness: ContractCheck[]; activity: Array<{ id: string; actor: string; action: string; occurredAt: string; source: "user" | "system" | "mock"; audit: false }>; execution: { externalContacted: false; importedRecords: 0; secretsExposed: false; downstreamActionsExecuted: false } }
export interface QaCheck { id: string; category: "contract" | "integration" | "accessibility" | "responsive" | "security" | "performance"; status: "passed" | "failed" | "blocked" | "not_run"; evidence: string; }
export interface QaReport { phase: 12; sourceCommit: string; checks: QaCheck[]; testsPassed: number; testsFailed: number; productionBuild: "passed" | "failed" | "not_run"; }
