// @ts-check
import { phase11Api, createPhase11IdempotencyKey } from "./phase11-api.js";
const state = { projectId: "prj_platform", providers: [], connections: [], runs: [], activity: [], audit: [], detail: null, receipt: null, loading: false, error: "" };
const path = () => new URLSearchParams(location.search).get("route") || location.hash.slice(1) || "/app/dashboard";
const isPhase11 = (value = path()) => value === "/app/integrations" || /^\/app\/projects\/[^/]+\/integrations$/.test(value) || value === "/app/activity" || value === "/app/audit";
const esc = (value = "") => String(value).replace(/[&<>"']/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#039;" })[char]);
const badge = (value) => `<span class="status ${esc(value)}">${esc(String(value).replaceAll("_", " "))}</span>`;
const date = (value) => value ? new Date(value).toLocaleString() : "Never";
const header = (eyebrow, title, copy) => `<div class="breadcrumbs"><span>SYNASE AI</span><span>/</span><b>${title}</b></div><header class="page-header"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p class="page-copy">${copy}</p></div></header>`;
const tabs = (active) => `<div class="page-tabs input-tabs" aria-label="Phase 11 navigation"><button class="input-tab ${active === "integrations" ? "active" : ""}" data-p11-route="/app/integrations">Integrations</button><button class="input-tab ${active === "activity" ? "active" : ""}" data-p11-route="/app/activity">Activity</button><button class="input-tab ${active === "audit" ? "active" : ""}" data-p11-route="/app/audit">Audit</button></div>`;
function integrations() {
  const providers = new Map(state.providers.map((item) => [item.id, item]));
  const cards = state.connections.map((item) => `<article class="card integration-card"><div class="card-head"><div><h2>${esc(item.displayName)}</h2><span class="small subtle">${esc(providers.get(item.providerId)?.name || item.providerId)} · Mock fixture</span></div>${badge(item.connectionStatus)}</div><div class="card-body"><dl class="integration-facts"><div><dt>Authorization</dt><dd>${badge(item.authorizationStatus)}</dd></div><div><dt>Health</dt><dd>${badge(item.health.status)}</dd></div><div><dt>Sync</dt><dd>${badge(item.syncStatus)}</dd></div><div><dt>Last sync</dt><dd>${esc(date(item.lastSyncedAt))}</dd></div></dl><div class="capability-list">${item.capabilities.map((value) => `<span>${esc(value)}</span>`).join("")}</div><p class="small subtle">Connection, authorization, health, and synchronization remain separate.</p><div class="control-bar"><button class="button" data-p11-action="health" data-id="${item.id}">Mock health check</button><button class="button primary" data-p11-action="sync" data-id="${item.id}">Mock sync</button><button class="button danger" data-p11-action="disconnect" data-id="${item.id}">Mock disconnect</button></div></div></article>`).join("");
  const catalog = state.providers.map((item) => `<article class="card provider-card"><div class="card-body"><div class="catalog-head"><span class="catalog-glyph">${esc(item.name[0])}</span>${badge(item.availabilityStatus)}</div><h2>${esc(item.name)}</h2><p>${esc(item.category.replaceAll("_", " "))} · ${esc(item.authorizationMethod.toUpperCase())}</p><div class="capability-list">${item.capabilities.map((value) => `<span>${esc(value)}</span>`).join("")}</div><button class="button" data-p11-action="connect" data-id="${item.id}" ${item.availabilityStatus !== "available" ? "disabled" : ""}>Create mock connection receipt</button></div></article>`).join("");
  const runs = state.runs.map((item) => `<tr><td><strong>${esc(item.id)}</strong><br><span class="small">${esc(item.type)}</span></td><td>${badge(item.status)}</td><td>${esc(date(item.startedAt))}</td><td>${item.importedRecords}</td><td>${item.externalContacted ? "Yes" : "No — mock only"}</td></tr>`).join("");
  return `${header("Phase 11 · Project integrations", "Integrations", "Typed provider, connection, authorization, health, synchronization, and run projections.")}${tabs("integrations")}<div class="alert">Provisional global route · Selected project: <code>${esc(state.projectId)}</code>. No provider is contacted and no data is imported.</div>${state.receipt ? `<div class="alert success" role="status">Mock receipt: ${esc(state.receipt.operation)} · external contacted: No · executed: No</div>` : ""}<section><div class="section-title"><div><h2>Project connections</h2><p class="small subtle">Providers and connections remain separate resources.</p></div></div><div class="phase11-grid">${cards}</div></section><section class="phase11-section"><div class="section-title"><h2>Available providers</h2></div><div class="provider-grid">${catalog}</div></section><section class="phase11-section"><div class="section-title"><h2>Integration runs</h2></div><div class="table-wrap"><table><thead><tr><th>Run</th><th>Status</th><th>Started</th><th>Imported</th><th>External contact</th></tr></thead><tbody>${runs}</tbody></table></div></section>`;
}
function activity() {
  const cards = state.activity.map((item) => `<article class="card activity-card"><div class="card-body"><div class="activity-heading"><div><strong>${esc(item.actor.name)}</strong><span>${esc(item.actor.type)} · ${esc(item.source)} event</span></div>${badge(item.outcome)}</div><h2>${esc(item.action.replaceAll(".", " · "))}</h2><p>${esc(item.target.type.replaceAll("_", " "))}: <strong>${esc(item.target.label)}</strong></p><div class="activity-meta"><span>${esc(item.domain)}</span><time>${esc(date(item.occurredAt))}</time><span class="proposal">Mock fixture</span></div></div></article>`).join("");
  return `${header("Phase 11 · Operational history", "Activity", "Project-scoped operational history with explicit actor, source, domain, outcome, and mock semantics.")}${tabs("activity")}<div class="alert">Activity is not an immutable or security-grade audit record.</div><form class="filter-panel" id="p11-activity-filter"><label>Actor<select name="actor"><option value="">All actors</option><option value="usr_satyam">Satyam Singh</option><option value="usr_maya">Maya Chen</option><option value="system">System</option></select></label><label>Action<input name="action" placeholder="integration"></label><label>Domain<select name="domain"><option value="">All domains</option><option>integrations</option><option>reports</option></select></label><label>From<input type="date" name="from"></label><button class="button">Apply filters</button></form><div class="activity-grid">${cards || `<section class="card empty"><div><h2>No matching activity</h2><p>Adjust filters and retry.</p></div></section>`}</div>`;
}
function audit() {
  const rows = state.audit.map((item) => `<tr><td><button class="link-cell" data-p11-action="detail" data-id="${item.id}">${esc(item.id)}</button></td><td><strong>${esc(item.actor.displayName)}</strong><br><span class="small">${esc(item.actor.type)}</span></td><td>${esc(item.action)}</td><td>${esc(item.resource.label)}</td><td>${badge(item.outcome)}</td><td>${esc(date(item.occurredAt))}</td></tr>`).join("");
  const detail = state.detail ? `<aside class="card audit-detail"><div class="card-head"><div><h2>Event detail</h2><span class="small subtle">Read-only immutable projection</span></div><button class="icon-btn" data-p11-action="close" aria-label="Close audit detail">×</button></div><div class="card-body"><dl class="audit-fields"><div><dt>Event ID</dt><dd>${esc(state.detail.id)}</dd></div><div><dt>Request ID</dt><dd><code>${esc(state.detail.requestId)}</code></dd></div><div><dt>Correlation ID</dt><dd><code>${esc(state.detail.correlationId)}</code></dd></div><div><dt>Actor</dt><dd>${esc(state.detail.actor.displayName)}</dd></div><div><dt>Metadata</dt><dd><pre>${esc(JSON.stringify(state.detail.metadata, null, 2))}</pre></dd></div></dl><div class="alert">Mock fixture · immutable: Yes · secret fields redacted or omitted.</div></div></aside>` : "";
  return `${header("Phase 11 · Read-only projection", "Audit", "Immutable project-scoped events with safe metadata and request/correlation identifiers.")}${tabs("audit")}<div class="alert">Provisional route · Mock fixtures do not claim security-grade completeness or retention.</div><form class="filter-panel" id="p11-audit-filter"><label>Actor<select name="actor"><option value="">All actors</option><option value="usr_satyam">Satyam Singh</option><option value="usr_maya">Maya Chen</option><option value="system">System</option></select></label><label>Action<input name="action" placeholder="integration"></label><label>Outcome<select name="outcome"><option value="">All outcomes</option><option>success</option><option>accepted</option><option>warning</option></select></label><button class="button">Apply filters</button></form><div class="audit-layout"><div class="table-wrap"><table><thead><tr><th>Event</th><th>Actor</th><th>Action</th><th>Resource</th><th>Outcome</th><th>Timestamp</th></tr></thead><tbody>${rows}</tbody></table></div>${detail}</div>`;
}
function installNav() {
  // Navigation is managed declaratively by the main shell
}
function render() {
  installNav(); if (!isPhase11()) return; const main = document.querySelector("#main"); if (!main) return;
  main.dataset.phase11View = path();
  if (state.loading) main.innerHTML = `<div class="loading"><div><div class="spinner"></div>Loading mock project data…</div></div>`;
  else if (state.error) main.innerHTML = `<section class="card empty"><div><h2>Unable to load</h2><p>${esc(state.error)}</p><button class="button" data-p11-action="retry">Retry</button></div></section>`;
  else main.innerHTML = path().includes("integrations") ? integrations() : path() === "/app/activity" ? activity() : audit();
}
async function load(filters = {}) {
  if (!isPhase11()) return; const routeProject = path().match(/^\/app\/projects\/([^/]+)\/integrations$/)?.[1];
  state.projectId = routeProject || document.querySelector("#project-switcher")?.value || state.projectId; state.loading = true; state.error = ""; render();
  try { if (path().includes("integrations")) { const [providers, connections, runs] = await Promise.all([phase11Api.listIntegrationProviders(), phase11Api.listIntegrationConnections(state.projectId), phase11Api.listIntegrationRuns(state.projectId)]); state.providers = providers.data; state.connections = connections.data; state.runs = runs.data; } else if (path() === "/app/activity") state.activity = (await phase11Api.listActivity(state.projectId, filters)).data; else state.audit = (await phase11Api.listAuditEvents(state.projectId, filters)).data; }
  catch (error) { state.error = error instanceof Error ? error.message : "Mock adapter error"; } finally { state.loading = false; render(); }
}
async function mutate(action, id) { const options = { idempotencyKey: createPhase11IdempotencyKey() }; const method = { connect:"connectIntegration", disconnect:"disconnectIntegration", health:"checkIntegrationHealth", sync:"syncIntegration" }[action]; state.receipt = (await phase11Api[method](state.projectId, id, options)).data; render(); }
document.addEventListener("click", async (event) => { const target = event.target instanceof Element ? event.target.closest("[data-p11-route],[data-p11-action]") : null; if (!target) return; const route = target.getAttribute("data-p11-route"); if (route) { location.hash = route; return; } const action = target.getAttribute("data-p11-action"); const id = target.getAttribute("data-id") || ""; try { if (["connect","disconnect","health","sync"].includes(action)) await mutate(action, id); else if (action === "detail") { state.detail = (await phase11Api.getAuditEvent(state.projectId, id)).data; render(); } else if (action === "close") { state.detail = null; render(); } else if (action === "retry") await load(); } catch (error) { state.error = error instanceof Error ? error.message : "Action failed"; render(); } });
document.addEventListener("submit", async (event) => { const form = event.target; if (!(form instanceof HTMLFormElement) || !form.id.startsWith("p11-")) return; event.preventDefault(); await load(Object.fromEntries(new FormData(form))); });
window.addEventListener("hashchange", () => load());
const observer = new MutationObserver(() => { installNav(); const main = document.querySelector("#main"); if (isPhase11() && main && main.dataset.phase11View !== path() && !state.loading) load(); }); observer.observe(document.body, { childList: true, subtree: true }); queueMicrotask(() => isPhase11() ? load() : installNav());
